### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by nguyenbaodanh** [SniperOO7/VIP-Premium-FULL-VERSION#1]
L 04/02/2021 - 12:43:29: [SM] Blaming: PUB\1hpvip-premium-v2.smx
L 04/02/2021 - 12:43:29: [SM] Call stack trace:
L 04/02/2021 - 12:43:29: [SM]   [0] GetClientHealth
L 04/02/2021 - 12:43:29: [SM]   [1] Line 234, 1hpvip-premium-v2.sp::OnPlayerDeath
L 04/02/2021 - 12:48:37: [SM] Exception reported: Client index 0 is invalid
L 04/02/2021 - 12:48:37: [SM] Blaming: PUB\1hpvip-premium-v2.smx
L 04/02/2021 - 12:48:37: [SM] Call stack trace:
L 04/02/2021 - 12:48:37: [SM]   [0] GetClientHealth
L 04/02/2021 - 12:48:37: [SM]   [1] Line 234, 1hpvip-premium-v2.sp::OnPlayerDeath
L 04/02/2021 - 13:04:01: Error log file session closed.

causing server crash sometime.

**Comment by SniperOO7** [comment]
This can't crash server, this can only stop code (like don't give HP to attacker), sorry for late answer (better to write me on steam)
